[package]
name = "geata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "geata"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
fs2.workspace = true
http.workspace = true
httpdate.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
instant-acme.workspace = true
openssl.workspace = true
parking_lot.workspace = true
pingora.workspace = true
serde.workspace = true
serde_json.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[lints]
workspace = true
