[package]
name = "geata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "geata"
path = "src/main.rs"

[dependencies]
base64.workspace = true
bitcoin.workspace = true
lightning-invoice.workspace = true
prost.workspace = true
http-body-util.workspace = true
rustls-pemfile.workspace = true
cdk.workspace = true
cdk-sqlite.workspace = true
redb.workspace = true
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
http.workspace = true
httpdate.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
instant-acme.workspace = true
openssl.workspace = true
parking_lot.workspace = true
pingora.workspace = true
serde.workspace = true
serde_json.workspace = true
rustls.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true

[dev-dependencies]
h2.workspace = true
tokio-rustls.workspace = true
nostr-sdk.workspace = true
tungstenite.workspace = true

[lints]
workspace = true
